# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201203_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(blank=True, default=317484349494),
        ),
    ]
