# Generated by Django 3.1.3 on 2020-12-03 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20201203_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 13, 13, 36, 360403, tzinfo=utc)),
        ),
    ]
