# Generated by Django 3.1.3 on 2020-12-05 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_auto_20201203_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 5, 9, 42, 57, 178917, tzinfo=utc)),
        ),
    ]
